### ISSUE TITLE
svychisq fails on certain tibble column types

### ISSUE THREAD

**Issue by ajdamico** [gergness/srvyr#23] opened 2016-09-22 01:50 UTC
hi, just an fyi, you might've already dealt with this..

stackoverflow.com/questions/39621028/error-with-svychisq-contrast-can-be-applied-to-factors-with-2-or-more-levels/

**Comment by mlaviolet** [comment] 2016-09-30 14:34
I had encountered this earlier. Is there a workaround or does this need to be addressed in the survey package? The svystandardize function seems to work with tbl_svy objects.

**Comment by gergness** [comment] 2016-09-30 15:43
Sorry, busy week (started a new job!) and haven't gotten to this. Thanks for bringing it up. 

I suspect that this will work as a short term hack (but haven't confirmed):

```r
sample <- structure(list(DISCWT = c(1.36973, 1.4144, 1.41222, 1.41222, 
1.4144, 1.4144, 1.41222, 1.41222, 1.4144, 1.41222, 1.41222, 1.41222, 
1.41222, 1.4144, 1.4144), COHORT = c(1997L, 2012L, 2000L, 2003L, 
2006L, 2006L, 2009L, 2012L, 2012L, 1997L, 2003L, 2006L, 2006L, 
2003L, 1997L), DIED = c(1L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 1L, 
0L, 0L, 0L, 0L, 1L)), row.names = c(NA, -15L), class = c("tbl_df", 
"tbl", "data.frame"), .Names = c("DISCWT", "COHORT", "DIED"))

sample_survey <- sample %>% as_survey_design(., weight = DISCWT)


# Fix
sample_survey$variables <- as.data.frame(sample_survey$variables)

svychisq(~DIED+COHORT, sample_survey)
```

srvyr can be updated to remove the tbl_df() class to prevent this kind of issue. I had considered that, but never got around to it.

**Comment by carlganz** [comment] 2016-09-30 16:20
The error occurs here: https://github.com/cran/survey/blob/master/R/surveychisq.R#L43

Issue is that when Lumley generates a vector with the values for the rows and the columns here: https://github.com/cran/survey/blob/master/R/surveychisq.R#L21

it is actually a one column tibble instead of a vector so when he calls `length` here: https://github.com/cran/survey/blob/master/R/surveychisq.R#L29

it gives 1 instead of the number of elements. It seems that tibble has generated a number of unintended problems in other packages. I know that tibble also breaks packages that use `is.null(df$foo)` to test if a column exists. 

Regards

**Comment by gergness** [comment] 2016-10-03 01:32
Hm, will take more work than I thought because of the database code. I'm trying to decide if I should make a new method for svychisq (and possibly more functions from survey) or try to preserve the variables as a `data.frame` instead of `tbl_df`.

It might be worth reporting to Dr. Lumley though, since the same thing happens if you pass a tbl_df to `svydesign()`, which will probably get more and more common.

```r
library(survey)
data(api)
dclus1<-svydesign(id=~dnum, weights=~pw, data=dplyr::as_data_frame(apiclus1), fpc=~fpc)

svychisq(~sch.wide+stype, dclus1)
```

**Closed** 2016-10-03 23:35 UTC

**Comment by gergness** [comment] 2016-10-03 23:37
Added a custom method for svychisq as a stopgap, hopefully the fix will be made in survey eventually.

If you come across a similar problem in other functions, please let me know.
