### ISSUE TITLE
`summarise_all` and `survey_mean` drops missing values for all vars rather than missing values for specific var

### ISSUE THREAD

**Issue by b-w-a** [gergness/srvyr#93] opened 2020-07-25 02:23 UTC
I tried to use `summarise_all` and `survey_mean` to get the means for multiple vars - however, the handling of missing data seems wrong. Instead of using missing values for each var - survey_mean uses missing values for all all the vars.

```
index <- as.character(1:500)
non_missing <- 1:500
missing <- c(1:498, NA, NA)

# actual values 
mean(missing, na.rm = T)
mean(non_missing, na.rm = T)

temp <- data.frame(index, non_missing, missing)

# mean works correctly 
temp %>% select(contains('missing')) %>% summarise_all(function(x) mean(x, na.rm = T))

# but survey mean drops obs in non-missing that correspond with missing 
dsn <- as_survey_design(temp)

dsn %>% select(contains('missing')) %>% summarise_all(function(x) survey_mean(x, na.rm = T))
```

**Comment by bschneidr** [comment] 2020-07-25 07:08
Hi Bryan,

Could you post the results of your code in this reprex? You might find it helpful to use the [`reprex`](https://reprex.tidyverse.org/articles/articles/learn-reprex.html) package for this. 

I'm running the latest GitHub version and can't seem to reproduce the issue you've posted.

``` r
library(tidyverse)
library(survey)
library(srvyr)

# Create example data
index <- as.character(1:500)
non_missing <- 1:500
missing <- c(1:498, NA, NA)

mean(missing, na.rm = T)
#> [1] 249.5
mean(non_missing, na.rm = T)
#> [1] 250.5

temp <- data.frame(index, non_missing, missing)

# Summarize using dplyr
dplyr_result <- temp %>% select(contains('missing')) %>% summarise_all(function(x) mean(x, na.rm = T))

# Summarize using srvyr
dsn <- as_survey_design(temp)

srvyr_result <- dsn %>% select(contains('missing')) %>% summarise_all(function(x) survey_mean(x, na.rm = T)) %>%
  select(non_missing, missing)

# Compare

srvyr_result$missing == dplyr_result$missing
#> [1] TRUE
srvyr_result$non_missing == dplyr_result$non_missing
#> [1] TRUE
```

<sup>Created on 2020-07-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gergness** [comment] 2020-07-25 16:32
Yea, this looks like a combination of two kind of confusing things:
1) R rounds to the nearest even number* when it hits a `.5` rather than how humans usually do it
2) `tibble`'s print method only shows three significant figures, so there was rounding in the display output.

``` r
library(srvyr)
#> 
#> Attaching package: 'srvyr'
#> The following object is masked from 'package:stats':
#> 
#>     filter

index <- as.character(1:500)
non_missing <- 1:500
missing <- c(1:498, NA, NA)

# actual values 
mean(missing, na.rm = T)
#> [1] 249.5
mean(non_missing, na.rm = T)
#> [1] 250.5

temp <- data.frame(index, non_missing, missing)

# mean works correctly 
temp %>% select(contains('missing')) %>% summarise_all(function(x) mean(x, na.rm = T))
#>   non_missing missing
#> 1       250.5   249.5

# but survey mean drops obs in non-missing that correspond with missing 
dsn <- as_survey_design(temp)

dsn %>% select(contains('missing')) %>% summarise_all(function(x) survey_mean(x, na.rm = T))
#> # A tibble: 1 x 4
#>   non_missing non_missing_se missing missing_se
#>         <dbl>          <dbl>   <dbl>      <dbl>
#> 1        250.           6.46    250.       6.45

## `data.frame` print method doesn't round
dsn %>% select(contains('missing')) %>% summarise_all(function(x) survey_mean(x, na.rm = T)) %>% as.data.frame()
#>   non_missing non_missing_se missing missing_se
#> 1       250.5       6.461424   249.5   6.448488
```

<sup>Created on 2020-07-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Closing for now, but let us know if you still think there's an error.

**Closed by gergness** 2020-07-25 16:32 UTC

**Comment by b-w-a** [comment] 2020-07-25 23:13
Thank you! I updated the package and figured out what was going on. It was not this, but when I tried the toy example and the results confirmed my suspicion (because of the rounding and just looking at the output), I thought this was the root cause. Thank you for the prompt attention!
